//! rayonet: SSH-transport task distribution.
//!
//! Where rayon fans data-parallel work across the cores of one machine, rayonet
//! fans task-parallel work across machines on a network. See `DECISIONS.md` and
//! `PLAN.md` at the repo root for the design and the phased build.

pub mod agent;
pub mod coordinator;
pub mod fleet;
pub mod framing;
pub mod observability;
pub mod process;
pub mod protocol;
pub mod provisioning;
pub mod ssh;
pub mod testing;
#[cfg(feature = "tui")]
pub mod tui;

/// Pull in the agent registry generated by `rayonet_build::extract()`.
///
/// Invoke once at the consumer's crate root, after its `build.rs` has called
/// `rayonet_build::extract()`. Expands to a
/// `__rayonet_registry()` function returning an [`agent::Registry`].
#[macro_export]
macro_rules! embed_microcrates {
    () => {
        fn __rayonet_registry() -> $crate::agent::Registry {
            include!(concat!(env!("OUT_DIR"), "/rayonet_registry.rs"))
        }
    };
}
